name: Build & Publish BERYL (Linux)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (clean)
        run: npm ci

      # Build and publish via Electron Forge (uses publisher-github in forge.config.ts)
      - name: Make & Publish (Linux)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Build for Linux and publish as a draft release
          npm run publish -- --platform=linux
